### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by kepitrion** [the-words/cocktail#2]
# Document System
 - [ ] CRUD
 - [ ] ACL System
 - [ ] Parser #4 

# User System
 - [ ] Permission system
 - [ ] Ban and ACL system
 - [ ] Login, logout and sign up
 - [ ] Login history
 - [ ] User information modification
 
# Discussion (Thread) System
 - [ ] Thread CRUD
 - [ ] Thread management system
